language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install libpcap0.8 libpcap0.8-dev valgrind

script:
    - make BIT=32 && make check BIT=32 && make valgrind-check BIT=32
    - make clean
    - make && make check && make valgrind-check

notifications:
    email:
      - hyzwowtools@gmail.com
